// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/components": {
    params: {};
  };
  "/projects": {
    params: {};
  };
  "/locations": {
    params: {};
  };
  "/shipping": {
    params: {};
  };
  "/settings": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/components" | "/projects" | "/locations" | "/shipping" | "/settings";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/components.tsx": {
    id: "routes/components";
    page: "/components";
  };
  "routes/projects.tsx": {
    id: "routes/projects";
    page: "/projects";
  };
  "routes/locations.tsx": {
    id: "routes/locations";
    page: "/locations";
  };
  "routes/shipping.tsx": {
    id: "routes/shipping";
    page: "/shipping";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/components": typeof import("./app/routes/components.tsx");
  "routes/projects": typeof import("./app/routes/projects.tsx");
  "routes/locations": typeof import("./app/routes/locations.tsx");
  "routes/shipping": typeof import("./app/routes/shipping.tsx");
  "routes/settings": typeof import("./app/routes/settings.tsx");
};